"""Compile a policy's syscall denylist into a cBPF program for bwrap's ``--seccomp``.

A denylist rather than an allowlist, so a syscall hozo has not seen stays permitted.

Syscall numbers come from ``syscalls.json``, generated by ``tools/gen_syscalls.py``.
"""

from __future__ import annotations

import functools
import importlib.resources as resources
import json
import platform
import struct
from typing import TYPE_CHECKING

from .errors import HozoError

if TYPE_CHECKING:  # runtime import would cycle: profiles -> seccomp -> policy -> profiles
    from .policy import ResolvedPolicy

# linux/bpf_common.h opcodes, pre-combined.
_LD_W_ABS = 0x20  # BPF_LD | BPF_W | BPF_ABS
_JEQ_K = 0x15  # BPF_JMP | BPF_JEQ | BPF_K
_JGE_K = 0x35  # BPF_JMP | BPF_JGE | BPF_K
_RET_K = 0x06  # BPF_RET | BPF_K

# struct seccomp_data offsets.
_NR_OFFSET = 0
_ARCH_OFFSET = 4

# AUDIT_ARCH_* tokens (linux/audit.h).
AUDIT_ARCH = {"x86_64": 0xC000003E, "aarch64": 0xC00000B7}

# x32 shares seccomp_data.arch with x86_64 but sets bit 30 in nr, so `jeq nr, 425` would
# miss `0x40000000 | 425`. The whole ABI is rejected instead.
_X32_SYSCALL_BIT = 0x40000000

_SECCOMP_RET_KILL_PROCESS = 0x80000000
_SECCOMP_RET_ERRNO = 0x00050000
_SECCOMP_RET_LOG = 0x7FFC0000
_SECCOMP_RET_ALLOW = 0x7FFF0000
_ENOSYS = 38

# 'errno' returns ENOSYS, the same answer as a kernel without the syscall, where 'kill'
# ends the process. 'log' permits the call; recording it needs kernel 4.14 and the action
# in /proc/sys/kernel/seccomp/actions_logged.
ACTIONS = {
    "errno": _SECCOMP_RET_ERRNO | _ENOSYS,
    "kill": _SECCOMP_RET_KILL_PROCESS,
    "log": _SECCOMP_RET_LOG,
}

_MAX_JUMP = 255  # cBPF jump offsets are u8


def _jump(here: int, target: int) -> int:
    """Branch offsets count from the next instruction."""
    return target - here - 1


def _instr(code: int, jt: int, jf: int, k: int) -> bytes:
    """One struct sock_filter; '=' gives 2+1+1+4 with no padding, in native byte order."""
    return struct.pack("=HBBI", code, jt, jf, k & 0xFFFFFFFF)


@functools.cache
def _tables() -> dict[str, dict[str, int]]:
    text = resources.files("hozo").joinpath("syscalls.json").read_text(encoding="utf-8")
    return json.loads(text)


def host_arch() -> str:
    machine = platform.machine()
    return "aarch64" if machine == "arm64" else machine


def syscall_table(arch: str) -> dict[str, int] | None:
    """Name -> number for this arch, or None if no table ships for it."""
    return _tables()[arch] if arch in AUDIT_ARCH else None


@functools.cache
def known_syscalls() -> frozenset[str]:
    """Every name valid on some supported arch, so profiles parse the same on any platform."""
    return frozenset().union(*_tables().values())


def build_seccomp_filter(policy: ResolvedPolicy, *, arch: str | None = None) -> bytes | None:
    """Compile ``policy.syscall_deny`` to cBPF, or None when no filter applies.

    Check arch, load nr, reject x32, one equality test per denied syscall, else allow.
    """
    if not policy.syscall_deny:
        return None

    arch = arch or host_arch()
    table = syscall_table(arch)
    # No table for this arch, so no filter, as on macOS. Failing here would make hozo
    # unusable on that host; `explain` reports the gap instead.
    if table is None:
        return None
    if policy.syscall_action not in ACTIONS:
        raise HozoError(f"invalid syscall action {policy.syscall_action!r}; expected one of {', '.join(ACTIONS)}")

    # Parsing vets names against every arch; this catches one absent on this arch, which
    # must not drop silently out of the list.
    unknown = sorted({name for name in policy.syscall_deny if name not in table})
    if unknown:
        raise HozoError(f"syscall not available on {arch}: {', '.join(unknown)}")
    numbers = sorted({table[name] for name in policy.syscall_deny})

    # Jumps are all forward to the three returns in the tail.
    guard_x32 = arch == "x86_64"
    head = 4 if guard_x32 else 3
    allow_idx = head + len(numbers)
    deny_idx = allow_idx + 1
    kill_idx = allow_idx + 2

    # Instruction 1 jumps furthest, so it bounds the list length.
    if _jump(1, kill_idx) > _MAX_JUMP:
        raise HozoError(f"seccomp denylist too long ({len(numbers)} syscalls); cBPF jump offsets are 8-bit")

    program = [
        _instr(_LD_W_ABS, 0, 0, _ARCH_OFFSET),
        _instr(_JEQ_K, 0, _jump(1, kill_idx), AUDIT_ARCH[arch]),
        _instr(_LD_W_ABS, 0, 0, _NR_OFFSET),
    ]
    if guard_x32:
        program.append(_instr(_JGE_K, _jump(3, kill_idx), 0, _X32_SYSCALL_BIT))
    for offset, number in enumerate(numbers):
        program.append(_instr(_JEQ_K, _jump(head + offset, deny_idx), 0, number))
    program.append(_instr(_RET_K, 0, 0, _SECCOMP_RET_ALLOW))
    program.append(_instr(_RET_K, 0, 0, ACTIONS[policy.syscall_action]))
    # A foreign arch (i386 on x86_64) numbers its syscalls differently, so the checks above
    # would not cover it.
    program.append(_instr(_RET_K, 0, 0, _SECCOMP_RET_KILL_PROCESS))

    return b"".join(program)
